name = "auth"
main = "src/index.ts"
compatibility_date = "2023-03-14"
usage_model = "bundled"
minify = true

route = { pattern = "api.stellargalactics.com/v2/user*", zone_name = "stellargalactics.com" }

#[env.production]
#route = { pattern = "api.stellargalactics.com/v2/user*", zone_name = "stellargalactics.com" }
#kv_namespaces = [ 
#  {binding = "INVITE_CODE", id = "c7b3656bdaed49fd896bddddb4932898", preview_id = "c7b3656bdaed49fd896bddddb4932898"}
#]

#[env.staging]
#route = { pattern = "staging.api.stellargalactics.com/v2/user*", zone_name = "stellargalactics.com" }
#workers_dev = true
#kv_namespaces = [
#  {binding = "INVITE_CODE", id = "c7b3656bdaed49fd896bddddb4932898", preview_id = "c7b3656bdaed49fd896bddddb4932898"}
#]

[[kv_namespaces]]
binding = "INVITE_CODE"
id = "c7b3656bdaed49fd896bddddb4932898"
preview_id = "c7b3656bdaed49fd896bddddb4932898"

[env.development.vars]
ENVIROMENT='development'

[[env.development.kv_namespaces]]
binding = "INVITE_CODE"
id = "c7b3656bdaed49fd896bddddb4932898"
preview_id = "c7b3656bdaed49fd896bddddb4932898"


# - AXIOM_TOKEN
# The necessary secrets are:
# - DATABASE_URL
# - VENGEANCE
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these