name = "mint"
main = "src/index.ts"
compatibility_date = "2023-03-14"
usage_model = "bundled"
minify = true
node_compat = true


# workers_dev = false

[env.production]
name = "mint"
route = { pattern = "api.stellargalactics.com/v2/mint*", zone_name = "stellargalactics.com" }
vars = {UPSTASH_REDIS_REST_URL="https://destined-barnacle-30856.upstash.io"}
r2_buckets = [
	{binding = "CYBORG_METADATA", bucket_name = "jpeg", preview_bucket_name = "jpeg"}
]
kv_namespaces = [ 
  {binding = "CYBORG_MINT", id = "fbbd08510282487088d6b4b56ffdb17a", preview_id = "fbbd08510282487088d6b4b56ffdb17a"},
  {binding = "INVITE_CODE", id = "c7b3656bdaed49fd896bddddb4932898", preview_id = "c7b3656bdaed49fd896bddddb4932898"}
]


[env.staging]
route = { pattern = "staging.api.stellargalactics.com/v2/mint*", zone_name = "stellargalactics.com" }
workers_dev = true

vars = {UPSTASH_REDIS_REST_URL="https://destined-barnacle-30856.upstash.io", ENVIROMENT='development'}
r2_buckets = [
	{binding = "CYBORG_METADATA", bucket_name = "jpeg", preview_bucket_name = "jpeg"}
]
kv_namespaces = [ 
  {binding = "CYBORG_MINT", id = "fbbd08510282487088d6b4b56ffdb17a", preview_id = "fbbd08510282487088d6b4b56ffdb17a"},
  {binding = "INVITE_CODE", id = "c7b3656bdaed49fd896bddddb4932898", preview_id = "c7b3656bdaed49fd896bddddb4932898"}
]

# [[kv_namespaces]]
# binding = "INVITE_CODE"
# id = "c7b3656bdaed49fd896bddddb4932898"
# preview_id = "c7b3656bdaed49fd896bddddb4932898"

# [[r2_buckets]]
# binding = "CYBORG_METADATA"
# bucket_name = "jpeg"
# preview_bucket_name = "jpeg"


# [env.development.vars]
# ENVIROMENT='development'

# [[env.development.kv_namespaces]]
# binding = "INVITE_CODE"
# id = "c7b3656bdaed49fd896bddddb4932898"
# preview_id = "c7b3656bdaed49fd896bddddb4932898"

# [[env.development.r2_buckets]]
# binding = "CYBORG_METADATA"
# bucket_name = "jpeg"
# preview_bucket_name = "jpeg"

[vars]
# UPSTASH_REDIS_REST_URL="https://destined-barnacle-30856.upstash.io"

